---
title: Workflow for Exporting Pedons from NASIS for the Fieldwook
author: "Stephen Roecker"
date: "10/2/2018"
output:
  html_document:
editor_options: 
  chunk_output_type: console
---


# Load packages

```{r}
library(sf)
library(sp)
library(soilDB)
```

# Get Project Extent

```{r}
prj_x <- read_sf("C:/workspace2/Multi_MLRA_selection_huc12s_diss.shp")
prj_x <- st_transform(prj_x, "+init=epsg:4326")
st_bbox(prj_x)

```


# Get siteiid and coordinates

```{sql}
EXEC SQL

SELECT CAST(siteiid AS INTEGER) siteiid, CAST(longstddecimaldegrees AS FLOAT) x, CAST(latstddecimaldegrees AS FLOAT) y

FROM site

WHERE (longstddecimaldegrees BETWEEN -88.07870 AND -76.90449) AND 
(latstddecimaldegrees BETWEEN 32.35203 AND 39.06249)
;.
```


# Get siteidd that intersect project extent

```{r}
p <- read.csv("C:/workspace2/dsm_prj_x.csv")
p <- p[complete.cases(p$x, p$y), ]
coordinates(p) <- ~ x + y
proj4string(p) <- CRS("+init=epsg:4326")
p2 <- st_as_sf(p)
write_sf(p2, dsn = "C:/workspace2/prj_x_pts.shp", layer = "prj_x_pts")

plot(as(prj_x, "Spatial"))
plot(p, add = TRUE)

p_o2 <- st_intersects(p2, prj_x, sparse = FALSE)

p3 <- p2[p_o2, ]

# create list and subset to manageable query
paste0(p3$siteiid, collapse = ", ")
```


# Query pedons

```{sql}
FROM

site    s                                     INNER JOIN
siteobs so ON so.siteiidref   = s.siteiid     INNER JOIN
pedon   p  ON p.siteobsiidref = so.siteobsiid

WHERE siteiid IN ()
;
```


# Fetch and save pedons
```{r}
fp <- fetchNASIS()
lp <- fetchNASISLabData()

save(fp, "C:/workspace2/dsm_fw_fp.Rdata")
save(lp, file = "C:/workspace2/dsm_fw_lp.Rdata")

load("C:/workspace2/dsm_fw_lp.Rdata")
```

